### PR TITLE
Add xls exractor

### PR DESCRIPTION
**Pull request by saylorsd**

### CODE REVIEW

**Comment by bsmithgall** [comment]
Can you add a test case for the new job?

**Comment by saylorsd** [comment]
@bsmithgall Test added.  Though I used `FileConnector` because I can't think of an effective way to mock an SFTP server.

also: the mock file just has one item as that's all they have available.  Once the add some more rows, I'll fill out that file a bit more/

**Comment by bsmithgall** [comment]
I think there should be mock connectors somewhere in the test base.

**Comment by bsmithgall** [comment]
This also fixes #34

**Comment by saylorsd** [comment]
@bsmithgall You fine with merging this, closing the issues, and opening a new one for testing `abestos_permits_pipeline` with a mock SFTP?  I'd like to get an instance running on our staging server for the jobs we have going. And then I can look into how to properly mock an SFTP server as I haven't had any immediate success.

**Comment by bsmithgall** [comment]
This looks good to me!

**Pull request merged**
