### PR TITLE
fixed pli_violations mock data

### PR DESCRIPTION
**Pull request by saylorsd**
Current PLI data taken directly from http://pittsburghpa.gov/pli/files/vet/pliExport.csv.

Don't ask me how, or why, but apparently it's now comma delimited.

### CODE REVIEW

**Comment by bsmithgall** [comment]
Lol OK

**Comment by bsmithgall** [comment]
Looks to still be UTF-8-BOM or other encoding.

**Comment by saylorsd** [comment]
Yeah, on that note, I did a quick and dirty read of the first couple bytes on new one and it starts with `0xef`, `0xbb` and `0xbf`, so I think it is [UTF-8 BOM](https://en.wikipedia.org/wiki/Byte_order_mark#UTF-8)

**Comment by bsmithgall** [comment]
You can test that by trying to open the file in python with the encoding
`utf-8-sig`

**Comment by saylorsd** [comment]
Good to know.  Thanks!

Steven Saylor

412-918-9630

**Pull request merged**
